/*
 * Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.event.simulator.randomdatafeedsimulation.core;


import org.apache.log4j.Logger;
import org.wso2.carbon.event.executionplandelpoyer.ExecutionPlanDeployer;
import org.wso2.carbon.event.executionplandelpoyer.ExecutionPlanDto;
import org.wso2.carbon.event.executionplandelpoyer.StreamDefinitionDto;
import org.wso2.carbon.event.executionplandelpoyer.Event;
import org.wso2.carbon.event.simulator.EventSimulator;
import org.wso2.carbon.event.simulator.exception.EventSimulationException;
import org.wso2.carbon.event.simulator.randomdatafeedsimulation.bean.FeedSimulationStreamAttributeDto;
import org.wso2.carbon.event.simulator.randomdatafeedsimulation.bean.RandomDataSimulationDto;
import org.wso2.carbon.event.simulator.randomdatafeedsimulation.utils.AttributeGenerator;
import org.wso2.carbon.event.simulator.utils.EventConverter;

import java.util.Arrays;


/**
 * This simulator simulates the execution plan by sending events. These events are generated by
 * generated random values according to given configuration.
 * <p>
 * This simulator class implements EventSimulator Interface
 * <p>
 * For simulation It generates Random values for an event using
 * {@link AttributeGenerator#generateAttributeValue(FeedSimulationStreamAttributeDto, String)}
 */
public class RandomDataEventSimulator implements EventSimulator {
    private static final Logger log = Logger.getLogger(RandomDataEventSimulator.class);

    /**
     * Flag used to pause the simulation.
     */
    public static volatile boolean isPaused = false;

    /**
     * Flag used to stop the simulation.
     */
    public static volatile boolean isStopped = false;

    /**
     * Initialize RandomDataEventSimulator to start the simulation
     */
    public RandomDataEventSimulator() {
    }

    /**
     * start simulation for given configuration
     *
     * @param randomDataSimulationConfig RandomDataSimulationDto
     */
    public void send(RandomDataSimulationDto randomDataSimulationConfig) {
        try {
            synchronized (this) {
                // TODO: 21/12/16 move this to starter 
                // TODO: 21/12/16 startsend events 
                sendEvent(ExecutionPlanDeployer.getInstance().getExecutionPlanDto(), randomDataSimulationConfig);
            }
        } catch (RuntimeException e) {
            throw new RuntimeException(e.getMessage());
        }
    }

    /**
     * send created event to siddhi input handler
     *
     * @param streamName Stream Name
     * @param event      Created Event
     */
    @Override
    public void send(String streamName, Event event) {
        try {
            /*
            get the input handler for particular input stream Name and send the event to that input handler
             */
            ExecutionPlanDeployer.getInstance().getInputHandlerMap().get(streamName).send(event.getEventData());
        } catch (InterruptedException e) {
            log.error("Error occurred during send event :" + e.getMessage());
        }
    }


    @Override
    public void resume() {
        synchronized (this) {
            this.notifyAll();
        }
    }


    private void sendEvent(ExecutionPlanDto executionPlanDto, RandomDataSimulationDto randomDataSimulationConfig) {
        int delay = randomDataSimulationConfig.getDelay();
        if (delay <= 0) {
            log.warn("Events will be sent continuously since the delay between events are set to "
                    + delay + "milliseconds");
            delay = 0;
        }


        double noOfEvents = randomDataSimulationConfig.getEvents();
        StreamDefinitionDto streamDefinitionDto = executionPlanDto.getInputStreamDtoMap().get(randomDataSimulationConfig.getStreamName());
        try {
                    /*
                    Generate dummy attributes to warm up Random Data generation. Because It takes some ms to generate 1st value.
                    It effects the delay between two events and trade off in performance also
                    So to reduce this draw back Initially it generates some dummy attributes
                    */

            String[] dummyAttribute = new String[randomDataSimulationConfig.getFeedSimulationStreamAttributeDto().size()];
            for (int i = 0; i < 5; i++) {
                for (int j = 0; j < randomDataSimulationConfig.getFeedSimulationStreamAttributeDto().size(); j++) {
                    dummyAttribute[j] = AttributeGenerator.generateAttributeValue(
                            randomDataSimulationConfig.getFeedSimulationStreamAttributeDto().get(j),
                            streamDefinitionDto.getStreamAttributeDtos().get(j).getAttributeType());
                }
            }
                    /*
                    We no longer need dummyAttribute. It will get garbage collected when there
                    are no more references to it.
                     */
            dummyAttribute = null;
                /*
                at this point starts to generate random  attribute values and convert it into siddhi event
                and send that event to input handler up to no of events reached to events given by user
                 */

            for (int i = 0; i < noOfEvents; i++) {
                int noOfAttributes = randomDataSimulationConfig.getFeedSimulationStreamAttributeDto().size();
                synchronized (this) {
                    if (isStopped) {
                        isStopped = false;
                        break;
                    }
                    if (isPaused) {
                        this.wait();
                    }
                    String[] attributeValue = new String[noOfAttributes];

                    //Generate Random values for each attribute
                    for (int j = 0; j < noOfAttributes; j++) {
                        attributeValue[j] = AttributeGenerator.generateAttributeValue(
                                randomDataSimulationConfig.getFeedSimulationStreamAttributeDto().get(j),
                                streamDefinitionDto.getStreamAttributeDtos().get(j).getAttributeType());
                    }

                    //convert Attribute values into event
                    Event event = EventConverter.eventConverter(randomDataSimulationConfig.getStreamName(), attributeValue, executionPlanDto);
                    //calculate percentage that event has send
                    /*
      Percentage of send events
     */
                    double percentage = ((i + 1) * 100) / noOfEvents;
                    System.out.println("Input Event " + Arrays.deepToString(event.getEventData()) + "Percentage :" + percentage);// TODO: 13/12/16 delete sout
                    //send the event to input handler
                    send(randomDataSimulationConfig.getStreamName(), event);
                    //delay between two events
                    if (delay > 0) {
                        Thread.sleep(delay);
                    }
                }
            }

        } catch (EventSimulationException e) {
            log.error("Event dropped due to Error occurred during generating an event" + e.getMessage());
        } catch (InterruptedException e) {
            log.error("Error occurred during send event" + e.getMessage());
        }
    }


}